// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("oracleobservability")
	ScopeName = "github.com/oracle-samples/otel-collector-exporter-oracleobservability/oracleobservabilityexporter"
)

const (
	LogsStability = component.StabilityLevelStable
)
